name: 'custom_postgres'
version: '1.0.0'
config-version: 2
profile: 'custom_postgres'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
 - "target"
 - "dbt_packages"
models:
  custom_postgres:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: table


log-path: /opt/airflow/dbt_logs